document.addEventListener('DOMContentLoaded',()=>{const yearEl=document.getElementById('currentYear');if(yearEl)yearEl.textContent=new Date().getFullYear();const animatedEls=document.querySelectorAll('[data-animate]');const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){const el=entry.target;const delay=el.dataset.delay?parseInt(el.dataset.delay):0;setTimeout(()=>{el.classList.add('animated');},delay);observer.unobserve(el);}});},{threshold:0.15});animatedEls.forEach(el=>observer.observe(el));const counters=document.querySelectorAll('.achieve-number');let countersStarted=false;const startCounters=()=>{counters.forEach(counter=>{const target=parseInt(counter.dataset.count);const duration=1800;const step=target/(duration/16);let current=0;const update=()=>{current+=step;if(current<target){counter.textContent=Math.floor(current);requestAnimationFrame(update);}else{counter.textContent=target;}};requestAnimationFrame(update);});};const counterSection=document.querySelector('.achievements-section');if(counterSection){const counterObserver=new IntersectionObserver((entries)=>{if(entries[0].isIntersecting&&!countersStarted){countersStarted=true;startCounters();counterObserver.disconnect();}},{threshold:0.3});counterObserver.observe(counterSection);}
const particleContainer=document.getElementById('heroParticles');if(particleContainer){const count=22;for(let i=0;i<count;i++){const p=document.createElement('div');p.classList.add('particle');const size=Math.random()*5+2;const left=Math.random()*100;const top=Math.random()*100;const duration=Math.random()*10+8;const delay=Math.random()*8;p.style.cssText=`
        width: ${size}px;
        height: ${size}px;
        left: ${left}%;
        top: ${top}%;
        animation-duration: ${duration}s;
        animation-delay: ${delay}s;
        opacity: ${Math.random() * 0.5 + 0.2};
        pointer-events: none;
      `;particleContainer.appendChild(p);}}
const navbar=document.querySelector('.main-navbar');if(navbar){window.addEventListener('scroll',()=>{if(window.scrollY>60){navbar.style.background='rgba(10, 26, 16, 0.97)';navbar.style.boxShadow='0 4px 30px rgba(0,0,0,0.25)';}else{navbar.style.background='';navbar.style.boxShadow='';}},{passive:true});}
const isTouchDevice=('ontouchstart'in window)||(navigator.maxTouchPoints>0);if(!isTouchDevice){const valueCards=document.querySelectorAll('.value-card-new');valueCards.forEach(card=>{card.addEventListener('mousemove',(e)=>{const rect=card.getBoundingClientRect();const x=e.clientX-rect.left;const y=e.clientY-rect.top;const cx=rect.width/2;const cy=rect.height/2;const rotX=((y-cy)/cy)*4;const rotY=((x-cx)/cx)*-4;card.style.transform=`perspective(600px) rotateX(${rotX}deg) rotateY(${rotY}deg) translateY(-5px)`;});card.addEventListener('mouseleave',()=>{card.style.transform='';});});}
document.addEventListener('touchstart',()=>{},{passive:true});document.addEventListener('touchmove',()=>{},{passive:true});});
