const IMAGES_P1=[{src:'img/pic-1.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 1'},{src:'img/pic-1.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 2'},{src:'img/pic-3.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 3'},{src:'img/pic-4.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 4'},{src:'img/pic-5.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 5'},{src:'img/pic-6.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 6'},{src:'img/pic-7.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 7'},{src:'img/pic-8.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 8'},{src:'img/pic-9.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 9'},{src:'img/pic-10.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 10'},{src:'img/pic-11.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 11'},{src:'img/pic-12.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 12'},{src:'img/pic-13.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 13'},{src:'img/pic-15.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 15'},{src:'img/pic-17.webp?v=20260604m2',title:'Purbachal SouthEast Valley — Photo 17'},];const IMAGES_P3=[{src:'img/coxs1.webp?v=20260604m2',title:"Ocean Breeze Hotel & Resort — Photo 1"},{src:'img/coxs2.webp?v=20260604m2',title:"Ocean Breeze Hotel & Resort — Photo 2"},{src:'img/coxs3.webp?v=20260604m2',title:"Ocean Breeze Hotel & Resort — Photo 3"},{src:'img/coxs4.webp?v=20260604m2',title:"Ocean Breeze Hotel & Resort — Photo 4"},{src:'img/coxs5.webp?v=20260604m2',title:"Ocean Breeze Hotel & Resort — Photo 5"},{src:'img/coxs6.webp?v=20260604m2',title:"Ocean Breeze Hotel & Resort — Photo 6"},{src:'img/coxs7.webp?v=20260604m2',title:"Ocean Breeze Hotel & Resort — Photo 7"},{src:'img/coxs8.webp?v=20260604m2',title:"Ocean Breeze Hotel & Resort — Photo 8"},];function createGallery(cfg){let cur=0;let autoOn=true;let timer=null;let lbIdx=0;const images=cfg.images;const total=images.length;const padTotal=String(total).padStart(2,'0');const grid=document.getElementById(cfg.thumbGridId);images.forEach((img,i)=>{const d=document.createElement('div');d.className='thumb-item'+(i===0?' active':'');d.dataset.idx=i;d.innerHTML=`
      <img src="${img.src}" alt="${img.title}" loading="lazy" decoding="async">
      <span class="tn">${String(i + 1).padStart(2, '0')}</span>
    `;d.addEventListener('click',()=>goTo(i));grid.appendChild(d);});function goTo(idx){cur=idx;const el=document.getElementById(cfg.mainImgId);el.classList.add('fading');setTimeout(()=>{el.src=images[idx].src;el.classList.remove('fading');},220);document.getElementById(cfg.titleId).textContent=images[idx].title;document.getElementById(cfg.counterId).textContent=String(idx+1).padStart(2,'0')+' / '+padTotal;grid.querySelectorAll('.thumb-item').forEach((t,i)=>t.classList.toggle('active',i===idx));grid.querySelectorAll('.thumb-item')[idx]?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});}
function navSlide(dir){goTo((cur+dir+total)%total);}
function startAuto(){timer=setInterval(()=>navSlide(1),4000);}
function stopAuto(){clearInterval(timer);}
function toggleAuto(){autoOn=!autoOn;document.getElementById(cfg.autoIconId).className=autoOn?'fa-solid fa-pause':'fa-solid fa-play';document.getElementById(cfg.autoTextId).textContent=autoOn?'Auto Slide On':'Auto Slide Off';document.getElementById(cfg.autoBtnId).classList.toggle('on',autoOn);autoOn?startAuto():stopAuto();}
function openLB(){lbIdx=cur;renderLB();document.getElementById('glightbox').classList.add('open');document.body.style.overflow='hidden';window.activeLB={close:closeLB,move:moveLB};}
function closeLB(){document.getElementById('glightbox').classList.remove('open');document.body.style.overflow='';}
function moveLB(dir){lbIdx=(lbIdx+dir+total)%total;renderLB();}
function renderLB(){document.getElementById('lbImg').src=images[lbIdx].src;document.getElementById('lbTitle').textContent=images[lbIdx].title;document.getElementById('lbCount').textContent=String(lbIdx+1).padStart(2,'0')+' / '+padTotal;}
let touchStartX=0;const sliderEl=document.getElementById(cfg.sliderWrapId);sliderEl.addEventListener('touchstart',e=>{touchStartX=e.changedTouches[0].screenX;},{passive:true});sliderEl.addEventListener('touchend',e=>{const diff=touchStartX-e.changedTouches[0].screenX;if(Math.abs(diff)>40)navSlide(diff>0?1:-1);},{passive:true});startAuto();return{goTo,navSlide,toggleAuto,openLB,closeLB,moveLB};}
const galleries={};galleries.p1=createGallery({images:IMAGES_P1,mainImgId:'mainImg1',titleId:'slideTitle1',counterId:'slideCounter1',thumbGridId:'thumbGrid1',autoBtnId:'autoBtn1',autoIconId:'autoIcon1',autoTextId:'autoText1',sliderWrapId:'slider-p1',});galleries.p3=createGallery({images:IMAGES_P3,mainImgId:'mainImg3',titleId:'slideTitle3',counterId:'slideCounter3',thumbGridId:'thumbGrid3',autoBtnId:'autoBtn3',autoIconId:'autoIcon3',autoTextId:'autoText3',sliderWrapId:'slider-p3',});window.activeLB={close:()=>{},move:()=>{},};document.getElementById('glightbox').addEventListener('click',function(e){if(e.target===this)window.activeLB.close();});document.addEventListener('keydown',function(e){if(!document.getElementById('glightbox').classList.contains('open'))return;if(e.key==='ArrowLeft')window.activeLB.move(-1);if(e.key==='ArrowRight')window.activeLB.move(1);if(e.key==='Escape')window.activeLB.close();});let lbTouchX=0;document.getElementById('glightbox').addEventListener('touchstart',e=>{lbTouchX=e.changedTouches[0].screenX;},{passive:true});document.getElementById('glightbox').addEventListener('touchend',e=>{const diff=lbTouchX-e.changedTouches[0].screenX;if(Math.abs(diff)>40)window.activeLB.move(diff>0?1:-1);},{passive:true});document.querySelectorAll('.proj-pill').forEach(btn=>{btn.addEventListener('click',function(){document.querySelectorAll('.proj-pill').forEach(b=>b.classList.remove('active'));this.classList.add('active');document.querySelectorAll('.project-panel').forEach(p=>p.classList.remove('active'));document.getElementById('panel-'+this.dataset.tab).classList.add('active');});});const revObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');revObserver.unobserve(e.target);}});},{threshold:0.1});document.querySelectorAll('.rev').forEach(el=>revObserver.observe(el));const yearEl=document.getElementById('footerYear');if(yearEl)yearEl.textContent=new Date().getFullYear();

